#!/bin/bash

make clean
make arch=x86_64
if [ $? -ne 0 ]; then
	echo "Build failed."
	exit 1
fi
#strip img/kernel.elf

dd if=/dev/zero of=mythos.img bs=512 count=4096  # Create the IMG file

# Setup IMG file with our own bootloader
sudo losetup /dev/loop0 mythos.img
sudo cp obj/MBR.bin /dev/loop0          # Overwrite the bootloader with our own
sudo losetup -d /dev/loop0

sfdisk mythos.img < mythos.img.layout   # Create partition table

# Create a FAT12 partition
sudo losetup /dev/loop0 mythos.img -o 32768
sudo mkdosfs /dev/loop0 -n "EFI System" # Format to FAT12

# Mount the FAT12 file system, and copy necessary files to it
sudo mount /dev/loop0 /mnt
sudo cp -r img/* /mnt
ls -al /mnt/EFI
sudo umount /mnt

sudo losetup -d /dev/loop0

# Setup the partition with our own bootloader
#sudo losetup /dev/loop0 mythos.img -o 33280
#sudo cp obj/VBR.bin /dev/loop0         # Overwrite the VBR boot code with our own
#sudo losetup -d /dev/loop0
