#!/bin/bash

sudo qemu-system-x86_64 \
    -drive if=pflash,format=raw,unit=0,file=/usr/share/ovmf/x64/OVMF_CODE.fd,readonly=on \
    -drive if=pflash,format=raw,unit=1,file=/usr/share/ovmf/x64/OVMF_VARS.fd \
    -drive if=ide,format=raw,file=mythos.img \
    -net none -no-reboot -s $1
