#!/bin/bash

CC=gcc

CFLAGS="-m32 -Wall -fno-stack-protector -ffreestanding -nostdinc -I../../include"

CRT=../../runtimes/C/include

$CC $CFLAGS -I$CRT -c HAL.c -o ../../lib/HAL.lib

cd x86
make
cd ..
